version: '3.8'

services:

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    image: 'share-it-gateway'
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHARE_IT_SERVER_URL=http://server:9090

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    image: 'share-it-server'
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    container_name: db
    image: 'postgres:15-alpine'
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
